### ISSUE TITLE
Could be much lighter without `underscore`

### ISSUE THREAD

**Issue by seangenabe** [diasdavid/remap-keys#1]
For a small library that just remaps keys, it could be so much lighter if it didn't use a toolbelt such as `underscore` as a dependency. You could go with just either vanilla <s>`Array.prototype.reduce`</s> or the modular [`lodash.reduce`](https://www.npmjs.com/package/lodash.reduce).

EDIT: Realized we can't use Array.prototype.reduce

**Comment by daviddias** [comment]
@seangenabe thank you, that sounds like a good idea, would you like to submit a PR?
